.TH CLIENT 1 "September 2026" "libmyutils 1.0" "User Commands"
.SH NAME
client \- test driver for the libmyutils string and file utility library
.SH SYNOPSIS
.B client
.SH DESCRIPTION
.B client
is a small driver program that demonstrates and tests the functions
provided by the
.B libmyutils
library, including string manipulation functions
.RI ( mystrlen ", " mystrcpy ", " mystrncpy ", " mystrcat )
and file utility functions
.RI ( wordCount ", " mygrep ).
.SH SEE ALSO
.BR mystrlen (3),
.BR mystrcpy (3),
.BR mystrncpy (3),
.BR mystrcat (3),
.BR wordCount (3),
.BR mygrep (3)
.SH AUTHOR
Samiq <bsdsf24m056@pucit.edu.pk>
